package main

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"os"
	"path/filepath"

	"github.com/Mikhalevich/argparser"
)

const (
	URLTemplate          = "http://duplo/%s/upload/"
	URLPermanentTemplate = "http://duplo/%s/permanent/upload/"
)

type Params struct {
	Storage     string `json:"storage"`
	isPermanent bool
	files       []string
}

func NewParams() *Params {
	return &Params{
		Storage:     "common",
		isPermanent: false,
	}
}

func (p *Params) url() string {
	template := URLTemplate
	if p.isPermanent {
		template = URLPermanentTemplate
	}
	return fmt.Sprintf(template, p.Storage)
}

func (p *Params) parseFiles() error {
	if argparser.NArg() <= 0 {
		return errors.New("No files for upload specified")
	}

	p.files = make([]string, 0, argparser.NArg())
	for i := 0; i < argparser.NArg(); i++ {
		p.files = append(p.files, argparser.Arg(i))
	}

	return nil
}

func loadParams() (*Params, error) {
	storage := argparser.String("s", "", "storage name to upload")
	isPermanent := argparser.Bool("p", false, "user permanent storage")

	basicParams := NewParams()
	params, err, gen := argparser.Parse(basicParams)

	if gen {
		return nil, errors.New("Config should be autogenerated")
	}

	p := params.(*Params)
	err = p.parseFiles()
	if err != nil {
		return nil, err
	}

	if *storage != "" {
		p.Storage = *storage
	}
	p.isPermanent = *isPermanent

	return p, err
}

func makeBodyReader(files []string) (io.Reader, string, error) {
	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	for _, fileName := range files {
		file, err := os.Open(fileName)
		if err != nil {
			return nil, "", err
		}

		baseName := filepath.Base(fileName)
		part, err := writer.CreateFormFile(baseName, baseName)
		if err != nil {
			return nil, "", err
		}

		_, err = io.Copy(part, file)
		if err != nil {
			return nil, "", err
		}
	}

	err := writer.Close()
	if err != nil {
		return nil, "", err
	}

	return body, writer.FormDataContentType(), nil
}

func upload(params *Params) error {
	body, contentType, err := makeBodyReader(params.files)
	if err != nil {
		return err
	}

	request, err := http.NewRequest(http.MethodPost, params.url(), body)
	if err != nil {
		return err
	}

	request.Header.Set("Content-Type", contentType)
	request.Close = true

	client := http.Client{}
	response, err := client.Do(request)
	if err != nil {
		return err
	}
	defer response.Body.Close()

	if response.StatusCode != http.StatusOK {
		return fmt.Errorf("Unable to upload file: %s", response.Status)
	}

	return nil
}

func main() {
	p, err := loadParams()
	if err != nil {
		fmt.Println(err)
		return
	}

	err = upload(p)
	if err != nil {
		fmt.Println(err)
		return
	}

	fmt.Println("Done...")
}
